name: QlikFront
title: QlikFront | Qlik Sense web development tips and tricks 
description: A blog for web developers / Qlik Sense Developers creating mashups, web apps and Qlik extensions. Made by
  Thomas Pessato.
tags:
  - qlik
  - qliksense
  - mashup
  - extensions
  - react
  - angularjs
  - angular
  - javascript
  - html
  - css
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: thomas@clusterdesign.com
disqus_username: disqus_username
